version: '3.8'


services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports: 
        - 3306:3306
    volumes: 
        - db:/var/lib/mysql
        - db/init.sql:/docker-entrypoint-initdb.d/init.sql

  migration: 
    build: . 
    env_file: .env
    command: 
        bash -c 'while !</dev/tcp/db/3306; do sleep 5; done; python manage.py migrate'
    volumes: 
        - .:/code
    depends_on: 
        - db

  web:
    build: . 
    env_file: .env 
    command: 
        bash -c 'while !</dev/tcp/db/3306; do sleep 5; done; python manage.py runserver 0.0.0.0:8000'
    volumes: 
        - .:/code
    stdin_open: true 
    tty: true 
    ports: 
        - 8000:8000

    depends_on: 
        - db
        - migration


volumes:
  db:
    driver: local