version: '3.9'


services:
  db:
    image: mysql:latest
    env_file: .env 
    ports: 
        - ${DB_PORT}:${DB_PORT}
    volumes: 
        - mysql:/var/lib/mysql

  migration: 
    build: . 
    env_file: .env
    command: 
        bash -c 'while !</dev/tcp/db/${DB_PORT}; do sleep 5; done; python manage.py migrate'
    volumes: 
        - .:/code
    depends_on: 
        - db

  web:
    build: . 
    env_file: .env 
    command: 
        bash -c 'while !</dev/tcp/db/${DB_PORT}; do sleep 5; done; python manage.py runserver 0.0.0.0:${WEB_PORT}'
    volumes: 
        - .:/code
    stdin_open: true 
    tty: true 
    ports: 
        - ${WEB_PORT}:8000

    depends_on: 
        - db
        - migration


volumes: 
    mysql: