version: '3.9'


services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports: 
        - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

  migration: 
    build: . 
    env_file: .env
    command: 
        bash -c 'while !</dev/tcp/mysql/3306; do sleep 10; done; python manage.py migrate'
    volumes: 
        - .:/code
    depends_on: 
        - mysql


  web:
    build: . 
    env_file: .env 
    command: 
        bash -c 'while !</dev/tcp/mysql/3306; do sleep 10; done; python manage.py runserver 0.0.0.0:8000'
    volumes: 
        - .:/code
    stdin_open: true 
    tty: true 
    ports: 
        - 8000:8000

    depends_on: 
        - mysql
        - migration


volumes:
  mysql: