CREATE DATABASE IF NOT EXISTS '${MYSQL_DATABASE}';
CREATE USER '${USER_NAME}'@'%' IDENTIFIED WITH mysql_native_password BY '${USER_PASSWORD}';
GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE}.* TO '${USER_NAME}'@'%';
FLUSH PRIVILEGES;