# Generated by Django 4.2 on 2023-04-13 02:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employees",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("cpf", models.CharField(max_length=11, unique=True)),
                ("rg", models.CharField(max_length=9, unique=True)),
                (
                    "gender",
                    models.TextField(
                        choices=[
                            ("Not informed", "Default"),
                            ("Male", "Male"),
                            ("Female", "Felame"),
                            ("Nonbinary", "Nonbinary"),
                            ("Agender", "Agender"),
                            ("Other", "Other"),
                        ],
                        default="Not informed",
                    ),
                ),
                (
                    "driver_license",
                    models.TextField(
                        choices=[
                            ("Not informed", "Default"),
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("AB", "Ab"),
                            ("AC", "Ac"),
                            ("AD", "Ad"),
                            ("AE", "Ae"),
                        ],
                        default="Not informed",
                    ),
                ),
                ("birth_date", models.DateField()),
                (
                    "salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("weekly_hours", models.TimeField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
