# Generated by Django 4.2 on 2023-04-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employees",
            name="weekly_hours",
            field=models.TimeField(default=0),
        ),
    ]
