# Generated by Django 4.2 on 2023-04-11 13:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Departament",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=48)),
            ],
        ),
        migrations.CreateModel(
            name="Roles",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.IntegerField(
                        choices=[("Employee", "Default"), ("Supervisor", "Supervisor")],
                        default="Employee",
                    ),
                ),
                (
                    "departament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="departaments.departament",
                    ),
                ),
            ],
        ),
    ]
