# Generated by Django 4.2 on 2023-04-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("departaments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departament",
            name="title",
            field=models.CharField(max_length=48, unique=True),
        ),
    ]
